### ISSUE TITLE
能否增加xlswriter扩展

### ISSUE THREAD

**Issue by run6** [hyperf/hyperf-docker#11]
https://xlswriter-docs.viest.me/zh-cn/an-zhuang/pecl-tui-jian

原本想自己通过apk add
但作者说apk add的有点问题，推荐使用pecl
所以，希望能支持以下

**Comment by limingxinleo** [comment]
不行的。。。不过可以帮你写个例子，你可以自己构建

**Comment by run6** [comment]
> 不行的。。。不过可以帮你写个例子，你可以自己构建

好吧。我自己写完了，感谢
