### ISSUE TITLE
Redis 异步队列 注解生产消息打印没有生效

### ISSUE THREAD

**Issue by surnamepp** [hyperf/hyperf-docker#12]
![image](https://user-images.githubusercontent.com/37924997/77638171-b53f7f80-6f91-11ea-9ab2-adc73777c5e3.png)
![image](https://user-images.githubusercontent.com/37924997/77638252-ce483080-6f91-11ea-90b6-fe6387d498e1.png)
![image](https://user-images.githubusercontent.com/37924997/77638270-d99b5c00-6f91-11ea-87ac-acd342e5f8eb.png)
![image](https://user-images.githubusercontent.com/37924997/77638345-f768c100-6f91-11ea-9723-4db442118fd3.png)
![image](https://user-images.githubusercontent.com/37924997/77638407-10717200-6f92-11ea-927e-9b21061920ca.png)
消费消息是重写AsyncQueueConsumer的handle是吗？

**Comment by surnamepp** [comment]
第三张图片的打印没有，按道理来说我不是可以在这步进行数据处理的么

**Comment by surnamepp** [comment]
issues提错地方了，这里能否帮忙看下

**Comment by limingxinleo** [comment]
Consumer的handle去掉，用默认的

**Comment by surnamepp** [comment]
![image](https://user-images.githubusercontent.com/37924997/77641062-621bfb80-6f96-11ea-9d55-0011bed04800.png)
![image](https://user-images.githubusercontent.com/37924997/77641096-6ea05400-6f96-11ea-9505-bb70615160a1.png)
去掉了，service的打印还是没有，如果不重写Consumer，我拿到数据处理在哪里写？是我理解错了吗

**Comment by limingxinleo** [comment]
就在你加了注解的方法体里面

**Comment by surnamepp** [comment]
那方法体的打印都没有走是什么情况，能麻烦分析下吗。

**Comment by limingxinleo** [comment]
channel改一下，你的redis是共享的？还是你本机

**Comment by limingxinleo** [comment]
然后composer update -o

**Comment by surnamepp** [comment]
redis是共享的。channel怎么改，是把配置改下么

**Comment by surnamepp** [comment]
![image](https://user-images.githubusercontent.com/37924997/77643390-3733a680-6f9a-11ea-8888-d66815468c1b.png)
![image](https://user-images.githubusercontent.com/37924997/77643416-49154980-6f9a-11ea-8949-c0de5fcde041.png)
Job是正常的，但是我如果想把数据加个数据，重新加入队列怎么半？
![image](https://user-images.githubusercontent.com/37924997/77643876-11f36800-6f9b-11ea-8abd-cc6f8e5d791b.png)

这样好像并不可以

**Comment by limingxinleo** [comment]
composer dump-autoload -o

**Comment by surnamepp** [comment]
好吧，传统模式job可以，先把项目上线了。有空在看注解了。谢谢🙏

**Comment by limingxinleo** [comment]
注解也可以的。。。只不过可能你没有重置代理类
