### ISSUE TITLE
build occur error on step5

### ISSUE THREAD

**Issue by tim0991** [hyperf/hyperf-docker#14]
```shell
cd hyperf-docker
docker build  .
```
![image](https://user-images.githubusercontent.com/26053904/80180595-afdb6080-8635-11ea-8d04-8db55de34489.png)

**Comment by limingxinleo** [comment]
![image](https://user-images.githubusercontent.com/16648551/80182589-d8655980-8639-11ea-8cec-f78ecc031732.png)
按照y以上流程打包。

另外，你搞个阿里云镜像加速器用一下吧

**Comment by tim0991** [comment]
啥都没改，隔了一会就好了重新build就好了
