### ISSUE TITLE
Class 'Swoole\Coroutine\PostgreSql

### ISSUE THREAD

**Issue by thcb3181** [hyperf/hyperf-docker#21]
您好，請問您是否有遇過此問題，Class 'Swoole\Coroutine\PostgreSql，您是怎麼解決的呢，我有嘗試再image裡抓下 ext-PostgreSql 仍然報錯，麻煩您了

**Comment by limingxinleo** [comment]
默认安装是没有 pgsql 这个扩展的，需要你自己装
