### ISSUE TITLE
hyperf/hyperf:7.3-alpine-v3.11-swoole 无php zlib扩展

### ISSUE THREAD

**Issue by ninvfeng** [hyperf/hyperf-docker#23]
hyperf/hyperf:7.3-alpine-v3.11-swoole 无php zlib扩展

`docker run -it hyperf/hyperf:7.3-alpine-v3.11-swoole ` 运行
`php -m ` 查看无zlib扩展

**Comment by limingxinleo** [comment]
自己装一个吧

**Comment by ninvfeng** [comment]
用 `apk add --no-cache php7-zlib` 装没反应

`docker run -it hyperf/hyperf:7.3-alpine-v3.11-swoole
/ # apk add --no-cache php7-zlib
fetch http://dl-cdn.alpinelinux.org/alpine/v3.11/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.11/community/x86_64/APKINDEX.tar.gz
fetch https://dl.bintray.com/php-alpine/v3.11/php-7.3/x86_64/APKINDEX.tar.gz
OK: 69 MiB in 90 packages`

php -m 查看还是没有, 装不上...

**Comment by limingxinleo** [comment]
自己编译安装呢？

**Comment by ninvfeng** [comment]
装不上, 先不管了, 用3.9 (hyperf/hyperf:7.3-alpine-v3.9-swoole) 是正常的

**Comment by limingxinleo** [comment]
我看了下。。好像是 php-alpine 库的问题

**Comment by limingxinleo** [comment]
用最新代码，应该解决了

**Comment by limingxinleo** [comment]
@ninvfeng 同学，抽空帮我测试一发啊

**Comment by ninvfeng** [comment]
可以了 :+1: 。 辛苦了, 谢谢 :grimacing:

**Comment by alaric8** [comment]
<img width="1365" height="94" alt="Image" src="https://github.com/user-attachments/assets/1a00f19b-8de0-4d1c-a1eb-757917a4d3b0" />我这个不知道什么问题我操了 有zlib 扩展
