### ISSUE TITLE
使用hyperf/hyperf:7.4-alpine-v3.9-cli版本时，使用easywechat发送外部请求会有问题

### ISSUE THREAD

**Issue by ljyljy0211** [hyperf/hyperf-docker#24]
使用hyperf/hyperf:7.4-alpine-v3.9-cli版本做底包的时候
在docker容器内发送外部请求会将请求结果打印在终端上，但是php代码是无法获取到返回值
我们在使用easywechat的时候发现的
是因为这个版本的swoole是4.5.5的，swoolle4.5.6以后才修复的
我们将底包升为hyperf/hyperf:7.4-alpine-v3.10-swoole-v4.6.3,则代码发送外部请求的时候，不会将讲过打印到终端，
php代码也能获取到返回值了

**Comment by limingxinleo** [comment]
hyperf/hyperf:7.4-alpine-v3.9-cli

这个 tag 已经废弃了

使用 

hyperf/hyperf:7.4-alpine-v3.11-swoole
