### ISSUE TITLE
项目下的dockefile 无法执行，，

### ISSUE THREAD

**Issue by liminworks** [hyperf/hyperf-docker#25]
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Composer could not find a composer.json file in /opt/www
To initialize a project, please create a composer.json file as described in the https://getcomposer.org/ "Getting Started" section

**Comment by liminworks** [comment]
不能作用超级管理员运行，，需要在镜像中添加非root用户

**Comment by limingxinleo** [comment]
不需要，直接 root 就可以
