### ISSUE TITLE
hyperf/hyperf:7.3-alpine-v3.9-base 使用的 dl.bintray.com apk 镜像源 Permission denied

### ISSUE THREAD

**Issue by jiang-wen** [hyperf/hyperf-docker#27]
现在 hyperf/hyperf:7.3-alpine-v3.9-swoole镜像无法执行update了，看提示是base镜像使用的 dl.bintray.com apk 镜像源 Permission denied

**Comment by iris-xie** [comment]
貌似是这个网站突然不维护了，卖给了杰蛙，我也被坑了，现在我们只能另外找别的基础镜像仓库

**Comment by ushell** [comment]
修复方案： https://dev.whatwedo.ch/whatwedo/php-alpine#dockerfile

hyperf的docker版本大概什么时候更新? 这个bintray仓库太坑了 :(

**Comment by limingxinleo** [comment]
@ushell 再等等，官方的人在看了

**Comment by limingxinleo** [comment]
fixed by https://github.com/hyperf/hyperf-docker/commit/adafdd4b934bbef8c2d74e8b699b9262f8ed710f

**Comment by yexk** [comment]
```
#4 0.627 fetch https://packages.whatwedo.ch/php-alpine/v3.11/php-7.4/x86_64/APKINDEX.tar.gz
#4 4.329 ERROR: https://packages.whatwedo.ch/php-alpine/v3.11/php-7.4: BAD signature
#4 4.329 WARNING: Ignoring APKINDEX.d8eca808.tar.gz: No such file or directory
#4 4.363 v3.11.11-46-g890023a769 [http://mirrors.ustc.edu.cn/alpine/v3.11/main]
#4 4.363 v3.11.11-24-g127ddb5cee [http://mirrors.ustc.edu.cn/alpine/v3.11/community]
```

为什么我的问题依旧？

**Comment by yexk** [comment]
packages.whatwedo.ch 这个网站也不能用了。。

**Comment by limingxinleo** [comment]
hyperf/hyperf:7.3-alpine-v3.11-base

使用最新版本

@yexk
