### ISSUE TITLE
底包不支持 iconv()

### ISSUE THREAD

**Issue by ljyljy0211** [hyperf/hyperf-docker#28]
Notice: iconv(): Wrong charset, conversion from `GBK' to `UTF-8//IGNORE' is not allowed

这个不支持此函数

**Comment by limingxinleo** [comment]
# fix aliyun oss wrong charset: https://github.com/aliyun/aliyun-oss-php-sdk/issues/101
RUN apk --no-cache --allow-untrusted --repository http://dl-cdn.alpinelinux.org/alpine/edge/community/ add gnu-libiconv
ENV LD_PRELOAD /usr/lib/preloadable_libiconv.so php

**Comment by limingxinleo** [comment]
RUN apk --no-cache --allow-untrusted --repository http://dl-cdn.alpinelinux.org/alpine/edge/community/ add gnu-libiconv=1.15-r2
ENV LD_PRELOAD /usr/lib/preloadable_libiconv.so
