### ISSUE TITLE
安装rdkafka扩展时 pecl not found

### ISSUE THREAD

**Issue by wsmike** [hyperf/hyperf-docker#36]
docker run --name hyperf \
--privileged -u root \
--entrypoint /bin/sh \
hyperf/hyperf:7.4-alpine-v3.11-swoole

apk add --no-cache librdkafka-dev \
&& pecl install rdkafka \
&& echo "extension=rdkafka.so" > /etc/php7/conf.d/rdkafka.ini

![1638515084(1)](https://user-images.githubusercontent.com/29519779/144570412-b23bc762-2b0b-4785-81e9-6ac3e97c599e.jpg)

**Comment by limingxinleo** [comment]
先自己装一下基础套件

**Comment by wsmike** [comment]
ok
