### ISSUE TITLE
构建出问题

### ISSUE THREAD

**Issue by nihaibao** [hyperf/hyperf-docker#4]
[DEBUG] Event Hyperf\Framework\Event\BootApplication handled by Hyperf\Di\Listener\BootApplicationListener listener.
[DEBUG] Event Hyperf\Framework\Event\BootApplication handled by Hyperf\Config\Listener\RegisterPropertyHandlerListener listener.
[DEBUG] Event Hyperf\Framework\Event\BootApplication handled by Hyperf\Paginator\Listener\PageResolverListener listener.
[DEBUG] Event Hyperf\Database\Model\Events\Booting handled by Hyperf\DbConnection\Listener\ModelEventListener listener.
[DEBUG] Event Hyperf\Database\Model\Events\Booted handled by Hyperf\DbConnection\Listener\ModelEventListener listener.
[DEBUG] Event Hyperf\Database\Model\Events\Booting handled by Hyperf\DbConnection\Listener\ModelEventListener listener.
[DEBUG] Event Hyperf\Database\Model\Events\Booted handled by Hyperf\DbConnection\Listener\ModelEventListener listener.
[DEBUG] Event Hyperf\Database\Model\Events\Booting handled by Hyperf\DbConnection\Listener\ModelEventListener listener.
[DEBUG] Event Hyperf\Database\Model\Events\Booted handled by Hyperf\DbConnection\Listener\ModelEventListener listener.
[DEBUG] Event Hyperf\Database\Model\Events\Booting handled by Hyperf\DbConnection\Listener\ModelEventListener listener.
[DEBUG] Event Hyperf\Database\Model\Events\Booted handled by Hyperf\DbConnection\Listener\ModelEventListener listener.
[DEBUG] Event Hyperf\Database\Model\Events\Booting handled by Hyperf\DbConnection\Listener\ModelEventListener listener.
[DEBUG] Event Hyperf\Database\Model\Events\Booted handled by Hyperf\DbConnection\Listener\ModelEventListener listener.
[DEBUG] Event Hyperf\Database\Model\Events\Booting handled by Hyperf\DbConnection\Listener\ModelEventListener listener.
[DEBUG] Event Hyperf\Database\Model\Events\Booted handled by Hyperf\DbConnection\Listener\ModelEventListener listener.
Proxy class create success.
The command '/bin/sh -c composer install --no-dev     && composer dump-autoload -o     && mv .env.${APP_ENV} .env     && php /opt/www/bin/hyperf.php di:init-proxy' returned a non-zero code: 1

FROM hyperf/hyperf:7.3-alpine-cli

如果改为hyperf/hyperf:7.2-alpine-cli构建正常

**Comment by limingxinleo** [comment]
用新的 init-proxy.sh 脚本初始化代理类
