### ISSUE TITLE
8.0/alpine/swoole/Dockerfile有错，build报错

### ISSUE THREAD

**Issue by aeonluck** [hyperf/hyperf-docker#41]
1， 第10行：
`FROM hyperf/hyperf:8.0-alpine-v${ALPINE_VERSION}-base`
`${ALPINE_VERSION}` 变量读取不到，当运行 `docker build -f Dockerfile .` 时会报错：
`failed to solve with frontend dockerfile.v0: failed to create LLB definition: docker.io/hyperf/hyperf:8.0-alpine-v-base: not found`

2，当手动修改Dockerfile中的${ALPINE_VERSION}为具体版本如 `3.14`时，则可以执行。

**Comment by limingxinleo** [comment]
这个不是让你这么用的。。。
