### ISSUE TITLE
不好意思，再问下，哪个版本支持m1, m2芯片？

### ISSUE THREAD

**Issue by hVenus** [hyperf/hyperf-docker#63]
哪个版本支持m1, m2芯片？

**Comment by limingxinleo** [comment]
好像都支持，默认都能通过 m系列芯片的参数来转

**Comment by hVenus** [comment]
swoole版本的虽然docker destop提示有问题，但是项目可以跑。
swow版本的就不行了，报错。
Undefined constant “Hyperf\Engine\SWOOLE_HOOK_ALL”

**Comment by limingxinleo** [comment]
hyperf/engine-swow 更新到最新版本
