### ISSUE TITLE
8.3-alpine-v3.19-swoole-5.1.3

### ISSUE THREAD

**Issue by Cluster2a** [hyperf/hyperf-docker#66]
Hey, according to https://github.com/swoole/swoole-src/releases the latest Version is 5.1.2. But you got an image out for 5.1.3:
https://hub.docker.com/layers/hyperf/hyperf/8.3-alpine-v3.19-swoole-5.1.3/images/sha256-9cba56cf0c0a1cf492f1e551a150b3881dfb196af28980a6993ee82851c4475a?context=explore

Is this a mistake?

**Comment by limingxinleo** [comment]
5.1.3 is a beta image.
